/** @type {import('cz-git').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'tokens',
        'themes',
        'utils',
        'components',
        'primitives',
        'storybook',
        'docs',
        'release',
        'repo',
      ],
    ],
    'scope-empty': [0, 'never'], // Allow empty scopes e.g. "chore: update dependencies"
    'subject-case': [0, 'never'], // Allow flexible casing in subject
  },
  prompt: {
    messages: {
      type: "Select the type of change that you're committing:",
      scope: 'Denote the SCOPE of this change (optional):',
      customScope: 'Denote the SCOPE of this change:',
      subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
      body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
      breaking: 'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
      footerPrefixesSelect: 'Select the ISSUES type of change_list by this change (optional):',
      customFooterPrefix: 'Input ISSUES prefix:',
      footer: 'List any ISSUES by this change. E.g.: #31, #34:\n',
      confirmCommit: 'Are you sure you want to proceed with the commit above?',
    },
    types: [
      { value: 'feat', name: 'feat:     ✨  A new feature or token' },
      { value: 'fix', name: 'fix:      🐛  A bug fix' },
      { value: 'docs', name: 'docs:     📝  Documentation only changes' },
      { value: 'style', name: 'style:    💄  Formatting, missing semi colons, etc.' },
      { value: 'refactor', name: 'refactor: ♻️   A code change that neither fixes a bug nor adds a feature' },
      { value: 'perf', name: 'perf:     ⚡️  A code change that improves performance' },
      { value: 'test', name: 'test:     ✅  Adding missing tests or correcting existing tests' },
      { value: 'build', name: 'build:    📦️  Changes that affect the build system or dependencies' },
      { value: 'ci', name: 'ci:       🎡  Changes to CI configuration files and scripts' },
      { value: 'chore', name: 'chore:    🔨  Other changes that do not modify src or test files' },
      { value: 'revert', name: 'revert:   ⏪️  Reverts a previous commit' },
    ],
    scopes: [
      { value: 'tokens', name: 'tokens:     @ripperdoc-chrome77/tokens and foundations' },
      { value: 'themes', name: 'themes:     @ripperdoc-chrome77/themes (Obsidian, Luminous)' },
      { value: 'utils', name: 'utils:      @ripperdoc-chrome77/utils (cn, DOM, focus)' },
      { value: 'components', name: 'components: @ripperdoc-chrome77/components' },
      { value: 'primitives', name: 'primitives: @ripperdoc-chrome77/primitives' },
      { value: 'storybook', name: 'storybook:  Storybook stories, addons, preview' },
      { value: 'docs', name: 'docs:       Documentation specifications' },
      { value: 'release', name: 'release:    Publishing, packaging, and Changesets' },
      { value: 'repo', name: 'repo:       Root repository configuration, toolchain' },
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
  },
};
